/********* Sample code generated by the curl command line tool **********
 * All curl_easy_setopt() options are documented at:
 * http://curl.haxx.se/libcurl/c/curl_easy_setopt.html
 ************************************************************************/
#include <curl/curl.h>
#include <string.h>
#include <regex.h> 

void set_session_id(char * location_header);
char * get_session_id();

static char __session_id__[] = "00000000000000000000000000000000";

size_t write_callback(char *ptr, size_t size, size_t nmemb, void *stream)
{
  
  char * token;
  char * ses_id;
  char ptr_cp[64];
  strcpy(ptr_cp,ptr);
  token = strtok (ptr_cp, ":");
  
  while(token != NULL) {
    if( strcmp(token,"Location") == 0){
      set_session_id(ptr);
      // strcpy( __session_id__, ses_id );
      printf("%s\n", get_session_id());
      return;
    }
    
    token = strtok (NULL, ":");  
  }  
  return nmemb; 
}



char* get_session_id(){
   return __session_id__;
} 



void set_session_id(char * location_header){
  regex_t regex;
  regmatch_t pmatch[64];
  int loc, re;
  re = regcomp(&regex, "/[0-9]+", REG_EXTENDED);
  loc = regexec(&regex, location_header, 1, pmatch, 0);
  
  //Should be synchronized for thread safety!
  strncpy (__session_id__, location_header + pmatch[0].rm_so +1, pmatch[0].rm_eo - pmatch[0].rm_so);
  __session_id__[pmatch[0].rm_eo - pmatch[0].rm_so] = '\0';
  regfree(&regex);
}
 

size_t my_read_func(void *ptr, size_t size, size_t nmemb, void *stream)
{
  return fread(ptr, size, nmemb, stream);
}



int main(int argc, char *argv[])
{
  CURLcode ret;
  CURL *hnd = curl_easy_init();
  curl_easy_setopt(hnd, CURLOPT_VERBOSE, 0);
  curl_easy_setopt(hnd, CURLOPT_URL, "http://localhost:4444/wd/hub/session");
  curl_easy_setopt(hnd, CURLOPT_NOPROGRESS, 1L);
  curl_easy_setopt(hnd, CURLOPT_HEADER, 1L);
  curl_easy_setopt(hnd, CURLOPT_POSTFIELDS, "{\"desiredCapabilities\":{\"browserName\":\"firefox\",\"version\":\"\",\"platform\":\"ANY\",\"javascriptEnabled\":true}}");
  curl_easy_setopt(hnd, CURLOPT_POSTFIELDSIZE_LARGE, (curl_off_t)-1);
  curl_easy_setopt(hnd, CURLOPT_USERAGENT, "curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3");
  curl_easy_setopt(hnd, CURLOPT_MAXREDIRS, 50L);
  // Could we use CURLOPT_WRITEDATA for the sessionId?
  // curl_easy_setopt(hnd, CURLOPT_WRITEDATA, outfile);
  curl_easy_setopt(hnd, CURLOPT_WRITEFUNCTION, write_callback);
  // curl_easy_setopt(hnd, CURLOPT_READFUNCTION, my_read_func);

  ret = curl_easy_perform(hnd);
  curl_easy_cleanup(hnd);

  /* Here is a list of options the curl code used that cannot get generated
     as source easily. You may select to either not use them or implement
     them yourself.

  CURLOPT_WRITEDATA set to a objectpointer
  CURLOPT_WRITEFUNCTION set to a functionpointer
  CURLOPT_READDATA set to a objectpointer
  CURLOPT_READFUNCTION set to a functionpointer
  CURLOPT_SEEKDATA set to a objectpointer
  CURLOPT_SEEKFUNCTION set to a functionpointer
  CURLOPT_ERRORBUFFER set to a objectpointer
  CURLOPT_STDERR set to a objectpointer
  CURLOPT_SOCKOPTFUNCTION set to a functionpointer
  CURLOPT_SOCKOPTDATA set to a objectpointer

  */
  return (int)ret;
}
/**** End of sample code ****/
